[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods"
]


[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
length_sort = true
