{
 "title": "NBA Dashboard",
 "time": { "from": "2022-11-03T23:00:00.000Z", "to": "2022-12-04T22:59:59.000Z" },
 "panels": [
  {
   "title": "FG Opp 10 Median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fg_opp_10_summary FROM nba_predictions LIMIT 50 "
    }
   ]
  },
  {
   "title": "FG Next Opp 10 Median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fg_nopp_10_summary FROM nba_predictions LIMIT 50 "
    }
   ]
  },
  {
   "title": "FG Opp 10 Column Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fg_opp_10_col_drift FROM nba_predictions LIMIT 50 "
    }
   ]
  },
  {
   "title": "FG Next Opp 10 Column Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fg_nopp_10_col_drift FROM nba_predictions LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM nba_predictions LIMIT 50 "
    }
   ]
  }
 ]
}